# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from eleven_labs_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_HISTORY = "/v1/history"
    V1_HISTORY_HISTORY_ITEM_ID = "/v1/history/{history_item_id}"
    V1_HISTORY_HISTORY_ITEM_ID_AUDIO = "/v1/history/{history_item_id}/audio"
    V1_HISTORY_DOWNLOAD = "/v1/history/download"
    V1_VOICES_VOICE_ID_SAMPLES_SAMPLE_ID = "/v1/voices/{voice_id}/samples/{sample_id}"
    V1_VOICES_VOICE_ID_SAMPLES_SAMPLE_ID_AUDIO = "/v1/voices/{voice_id}/samples/{sample_id}/audio"
    V1_TEXTTOSPEECH_VOICE_ID = "/v1/text-to-speech/{voice_id}"
    V1_TEXTTOSPEECH_VOICE_ID_STREAM = "/v1/text-to-speech/{voice_id}/stream"
    V1_SPEECHTOSPEECH_VOICE_ID = "/v1/speech-to-speech/{voice_id}"
    V1_SPEECHTOSPEECH_VOICE_ID_STREAM = "/v1/speech-to-speech/{voice_id}/stream"
    V1_VOICEGENERATION_GENERATEVOICE_PARAMETERS = "/v1/voice-generation/generate-voice/parameters"
    V1_VOICEGENERATION_GENERATEVOICE = "/v1/voice-generation/generate-voice"
    V1_VOICEGENERATION_CREATEVOICE = "/v1/voice-generation/create-voice"
    V1_USER_SUBSCRIPTION = "/v1/user/subscription"
    V1_USER = "/v1/user"
    V1_VOICES = "/v1/voices"
    V1_VOICES_SETTINGS_DEFAULT = "/v1/voices/settings/default"
    V1_VOICES_VOICE_ID_SETTINGS = "/v1/voices/{voice_id}/settings"
    V1_VOICES_VOICE_ID = "/v1/voices/{voice_id}"
    V1_VOICES_VOICE_ID_SETTINGS_EDIT = "/v1/voices/{voice_id}/settings/edit"
    V1_VOICES_ADD = "/v1/voices/add"
    V1_VOICES_VOICE_ID_EDIT = "/v1/voices/{voice_id}/edit"
    V1_VOICES_ADD_PUBLIC_USER_ID_VOICE_ID = "/v1/voices/add/{public_user_id}/{voice_id}"
    V1_PROJECTS = "/v1/projects"
    V1_PROJECTS_ADD = "/v1/projects/add"
    V1_PROJECTS_PROJECT_ID = "/v1/projects/{project_id}"
    V1_PROJECTS_PROJECT_ID_CONVERT = "/v1/projects/{project_id}/convert"
    V1_PROJECTS_PROJECT_ID_SNAPSHOTS = "/v1/projects/{project_id}/snapshots"
    V1_PROJECTS_PROJECT_ID_SNAPSHOTS_PROJECT_SNAPSHOT_ID_STREAM = "/v1/projects/{project_id}/snapshots/{project_snapshot_id}/stream"
    V1_PROJECTS_PROJECT_ID_CHAPTERS = "/v1/projects/{project_id}/chapters"
    V1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID = "/v1/projects/{project_id}/chapters/{chapter_id}"
    V1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_CONVERT = "/v1/projects/{project_id}/chapters/{chapter_id}/convert"
    V1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_SNAPSHOTS = "/v1/projects/{project_id}/chapters/{chapter_id}/snapshots"
    V1_PROJECTS_PROJECT_ID_CHAPTERS_CHAPTER_ID_SNAPSHOTS_CHAPTER_SNAPSHOT_ID_STREAM = "/v1/projects/{project_id}/chapters/{chapter_id}/snapshots/{chapter_snapshot_id}/stream"
    V1_PROJECTS_PROJECT_ID_UPDATEPRONUNCIATIONDICTIONARIES = "/v1/projects/{project_id}/update-pronunciation-dictionaries"
    V1_DUBBING = "/v1/dubbing"
    V1_DUBBING_DUBBING_ID = "/v1/dubbing/{dubbing_id}"
    V1_DUBBING_DUBBING_ID_AUDIO_LANGUAGE_CODE = "/v1/dubbing/{dubbing_id}/audio/{language_code}"
    ADMIN_ADMIN_URL_PREFIX_SSOPROVIDER = "/admin/{admin_url_prefix}/sso-provider"
    V1_MODELS = "/v1/models"
    V1_AUDIONATIVE = "/v1/audio-native"
    V1_SHAREDVOICES = "/v1/shared-voices"
    V1_PRONUNCIATIONDICTIONARIES_ADDFROMFILE = "/v1/pronunciation-dictionaries/add-from-file"
    ADMIN_N8ENYLACGD_VANITYLINK_VANITY_LINK_ID_UPDATE = "/admin/n8enylacgd/vanity-link/{vanity_link_id}/update"
    ADMIN_N8ENYLACGD_VANITYLINK_VANITY_LINK_ID_DELETE = "/admin/n8enylacgd/vanity-link/{vanity_link_id}/delete"
    ADMIN_N8ENYLACGD_VANITYLINKS = "/admin/n8enylacgd/vanity-links"
    ADMIN_N8ENYLACGD_VANITYLINK_SLUG = "/admin/n8enylacgd/vanity-link/{slug}"
    ADMIN_N8ENYLACGD_COUPON_PROMOCODE_ARCHIVE = "/admin/n8enylacgd/coupon/{promocode}/archive"
    ADMIN_N8ENYLACGD_COUPONS = "/admin/n8enylacgd/coupons"
    DOCS = "/docs"
    V1_PRONUNCIATIONDICTIONARIES_PRONUNCIATION_DICTIONARY_ID = "/v1/pronunciation-dictionaries/{pronunciation_dictionary_id}"
