# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from eleven_labs_python_sdk import schemas  # noqa: F401


class InvoiceResponseModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "amount_due_cents",
            "next_payment_attempt_unix",
        }
        
        class properties:
            amount_due_cents = schemas.IntSchema
            next_payment_attempt_unix = schemas.IntSchema
            __annotations__ = {
                "amount_due_cents": amount_due_cents,
                "next_payment_attempt_unix": next_payment_attempt_unix,
            }
    
    amount_due_cents: MetaOapg.properties.amount_due_cents
    next_payment_attempt_unix: MetaOapg.properties.next_payment_attempt_unix
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount_due_cents"]) -> MetaOapg.properties.amount_due_cents: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["next_payment_attempt_unix"]) -> MetaOapg.properties.next_payment_attempt_unix: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount_due_cents", "next_payment_attempt_unix", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount_due_cents"]) -> MetaOapg.properties.amount_due_cents: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["next_payment_attempt_unix"]) -> MetaOapg.properties.next_payment_attempt_unix: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount_due_cents", "next_payment_attempt_unix", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        amount_due_cents: typing.Union[MetaOapg.properties.amount_due_cents, decimal.Decimal, int, ],
        next_payment_attempt_unix: typing.Union[MetaOapg.properties.next_payment_attempt_unix, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InvoiceResponseModel':
        return super().__new__(
            cls,
            *args,
            amount_due_cents=amount_due_cents,
            next_payment_attempt_unix=next_payment_attempt_unix,
            _configuration=_configuration,
            **kwargs,
        )
