# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from eleven_labs_python_sdk import schemas  # noqa: F401


class SampleResponseModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "size_bytes",
            "mime_type",
            "file_name",
            "sample_id",
            "hash",
        }
        
        class properties:
            sample_id = schemas.StrSchema
            file_name = schemas.StrSchema
            mime_type = schemas.StrSchema
            size_bytes = schemas.IntSchema
            hash = schemas.StrSchema
            __annotations__ = {
                "sample_id": sample_id,
                "file_name": file_name,
                "mime_type": mime_type,
                "size_bytes": size_bytes,
                "hash": hash,
            }
    
    size_bytes: MetaOapg.properties.size_bytes
    mime_type: MetaOapg.properties.mime_type
    file_name: MetaOapg.properties.file_name
    sample_id: MetaOapg.properties.sample_id
    hash: MetaOapg.properties.hash
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sample_id"]) -> MetaOapg.properties.sample_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file_name"]) -> MetaOapg.properties.file_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mime_type"]) -> MetaOapg.properties.mime_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["size_bytes"]) -> MetaOapg.properties.size_bytes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hash"]) -> MetaOapg.properties.hash: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["sample_id", "file_name", "mime_type", "size_bytes", "hash", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sample_id"]) -> MetaOapg.properties.sample_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file_name"]) -> MetaOapg.properties.file_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mime_type"]) -> MetaOapg.properties.mime_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["size_bytes"]) -> MetaOapg.properties.size_bytes: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hash"]) -> MetaOapg.properties.hash: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["sample_id", "file_name", "mime_type", "size_bytes", "hash", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        size_bytes: typing.Union[MetaOapg.properties.size_bytes, decimal.Decimal, int, ],
        mime_type: typing.Union[MetaOapg.properties.mime_type, str, ],
        file_name: typing.Union[MetaOapg.properties.file_name, str, ],
        sample_id: typing.Union[MetaOapg.properties.sample_id, str, ],
        hash: typing.Union[MetaOapg.properties.hash, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SampleResponseModel':
        return super().__new__(
            cls,
            *args,
            size_bytes=size_bytes,
            mime_type=mime_type,
            file_name=file_name,
            sample_id=sample_id,
            hash=hash,
            _configuration=_configuration,
            **kwargs,
        )
