# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.admin_n8enylacgd_coupon_promocode_archive.post import ArchiveCouponPromocodePost
from eleven_labs_python_sdk.paths.admin_n8enylacgd_vanity_link_vanity_link_id_update.post import EditVanityLink
from eleven_labs_python_sdk.paths.admin_n8enylacgd_coupons.get import GetAllCoupons
from eleven_labs_python_sdk.paths.admin_n8enylacgd_vanity_links.get import GetAllVanityLinks
from eleven_labs_python_sdk.paths.admin_n8enylacgd_vanity_link_slug.get import GetVanityLink
from eleven_labs_python_sdk.paths.admin_n8enylacgd_vanity_link_vanity_link_id_delete.post import RemoveVanityLink
from eleven_labs_python_sdk.apis.tags.admin_api_raw import AdminApiRaw


class AdminApi(
    ArchiveCouponPromocodePost,
    EditVanityLink,
    GetAllCoupons,
    GetAllVanityLinks,
    GetVanityLink,
    RemoveVanityLink,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AdminApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AdminApiRaw(api_client)
