# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.v1_projects_add.post import CreateNewProjectRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id.delete import DeleteByIdRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_chapters_chapter_id.delete import DeleteChapterByIdRaw
from eleven_labs_python_sdk.paths.v1_projects.get import GetAllProjectsRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id.get import GetByIdRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_chapters_chapter_id.get import GetChapterByIdRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_chapters_chapter_id_snapshots.get import GetChapterSnapshotsRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_chapters.get import ListChaptersRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_snapshots.get import ListSnapshotsRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_chapters_chapter_id_convert.post import StartChapterConversionRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_convert.post import StartConversionRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_snapshots_project_snapshot_id_stream.post import StreamAudioFromSnapshotRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_chapters_chapter_id_snapshots_chapter_snapshot_id_stream.post import StreamAudioFromSnapshotPostRaw
from eleven_labs_python_sdk.paths.v1_projects_project_id_update_pronunciation_dictionaries.post import UpdatePronunciationDictionariesRaw


class ProjectsApiRaw(
    CreateNewProjectRaw,
    DeleteByIdRaw,
    DeleteChapterByIdRaw,
    GetAllProjectsRaw,
    GetByIdRaw,
    GetChapterByIdRaw,
    GetChapterSnapshotsRaw,
    ListChaptersRaw,
    ListSnapshotsRaw,
    StartChapterConversionRaw,
    StartConversionRaw,
    StreamAudioFromSnapshotRaw,
    StreamAudioFromSnapshotPostRaw,
    UpdatePronunciationDictionariesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
