# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.v1_speech_to_speech_voice_id.post import CreateWithVoice
from eleven_labs_python_sdk.paths.v1_speech_to_speech_voice_id_stream.post import CreateWithVoice0
from eleven_labs_python_sdk.apis.tags.speech_to_speech_api_raw import SpeechToSpeechApiRaw


class SpeechToSpeechApi(
    CreateWithVoice,
    CreateWithVoice0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SpeechToSpeechApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SpeechToSpeechApiRaw(api_client)
