# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.v1_history_history_item_id.delete import DeleteHistoryItemById
from eleven_labs_python_sdk.paths.v1_history_download.post import DownloadHistoryItems
from eleven_labs_python_sdk.paths.v1_history.get import GetGeneratedAudioMetadata
from eleven_labs_python_sdk.paths.v1_history_history_item_id_audio.get import GetHistoryItemAudio
from eleven_labs_python_sdk.paths.v1_history_history_item_id.get import GetHistoryItemById
from eleven_labs_python_sdk.apis.tags.speech_history_api_raw import SpeechHistoryApiRaw


class SpeechHistoryApi(
    DeleteHistoryItemById,
    DownloadHistoryItems,
    GetGeneratedAudioMetadata,
    GetHistoryItemAudio,
    GetHistoryItemById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SpeechHistoryApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SpeechHistoryApiRaw(api_client)
