# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.v1_voice_generation_create_voice.post import CreateVoiceRaw
from eleven_labs_python_sdk.paths.v1_voice_generation_generate_voice.post import GenerateRandomVoiceRaw
from eleven_labs_python_sdk.paths.v1_voice_generation_generate_voice_parameters.get import GetVoiceGenerationParametersRaw


class VoiceGenerationApiRaw(
    CreateVoiceRaw,
    GenerateRandomVoiceRaw,
    GetVoiceGenerationParametersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
