# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.v1_voices_add_public_user_id_voice_id.post import AddToCollection
from eleven_labs_python_sdk.paths.v1_voices_add.post import AddVoiceToCollection
from eleven_labs_python_sdk.paths.v1_voices_voice_id.delete import DeleteById
from eleven_labs_python_sdk.paths.v1_voices_voice_id_settings_edit.post import EditSettingsPost
from eleven_labs_python_sdk.paths.v1_voices_settings_default.get import GetDefaultVoiceSettings
from eleven_labs_python_sdk.paths.v1_voices_voice_id_settings.get import GetSettings
from eleven_labs_python_sdk.paths.v1_shared_voices.get import GetSharedVoices
from eleven_labs_python_sdk.paths.v1_voices_voice_id.get import GetVoiceMetadata
from eleven_labs_python_sdk.paths.v1_voices.get import ListAllVoices
from eleven_labs_python_sdk.paths.v1_voices_voice_id_edit.post import UpdateVoiceById
from eleven_labs_python_sdk.apis.tags.voices_api_raw import VoicesApiRaw


class VoicesApi(
    AddToCollection,
    AddVoiceToCollection,
    DeleteById,
    EditSettingsPost,
    GetDefaultVoiceSettings,
    GetSettings,
    GetSharedVoices,
    GetVoiceMetadata,
    ListAllVoices,
    UpdateVoiceById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VoicesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VoicesApiRaw(api_client)
