# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from eleven_labs_python_sdk.paths.admin_admin_url_prefix_sso_provider.get import GetSsoProviderAdmin
from eleven_labs_python_sdk.apis.tags.workspace_api_raw import WorkspaceApiRaw


class WorkspaceApi(
    GetSsoProviderAdmin,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkspaceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkspaceApiRaw(api_client)
