# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import eleven_labs_python_sdk
from eleven_labs_python_sdk.model.body_generate_a_random_voice_v1_voice_generation_generate_voice_post import BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
from eleven_labs_python_sdk import configuration


class TestBodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost(unittest.TestCase):
    """BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
