# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import eleven_labs_python_sdk
from eleven_labs_python_sdk.model.body_creates_audio_native_enabled_project_v1_audio_native_post import BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
from eleven_labs_python_sdk import configuration


class TestBodyCreatesAudioNativeEnabledProjectV1AudioNativePost(unittest.TestCase):
    """BodyCreatesAudioNativeEnabledProjectV1AudioNativePost unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
