# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import eleven_labs_python_sdk
from eleven_labs_python_sdk.model.body_create_a_previously_generated_voice_v1_voice_generation_create_voice_post_labels import BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePostLabels
from eleven_labs_python_sdk import configuration


class TestBodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePostLabels(unittest.TestCase):
    """BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePostLabels unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
