# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from eleven_labs_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from eleven_labs_python_sdk.api_response import AsyncGeneratorResponse
from eleven_labs_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from eleven_labs_python_sdk import schemas  # noqa: F401

from eleven_labs_python_sdk.model.get_library_voices_response_model import GetLibraryVoicesResponseModel as GetLibraryVoicesResponseModelSchema
from eleven_labs_python_sdk.model.http_validation_error import HTTPValidationError as HTTPValidationErrorSchema

from eleven_labs_python_sdk.type.http_validation_error import HTTPValidationError
from eleven_labs_python_sdk.type.get_library_voices_response_model import GetLibraryVoicesResponseModel

from ...api_client import Dictionary
from eleven_labs_python_sdk.pydantic.get_library_voices_response_model import GetLibraryVoicesResponseModel as GetLibraryVoicesResponseModelPydantic
from eleven_labs_python_sdk.pydantic.http_validation_error import HTTPValidationError as HTTPValidationErrorPydantic

# Query params
PageSizeSchema = schemas.IntSchema
CategorySchema = schemas.StrSchema
GenderSchema = schemas.StrSchema
AgeSchema = schemas.StrSchema
AccentSchema = schemas.StrSchema
SearchSchema = schemas.StrSchema


class UseCasesSchema(
    schemas.ListSchema
):


    class MetaOapg:
        items = schemas.StrSchema

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'UseCasesSchema':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> MetaOapg.items:
        return super().__getitem__(i)


class DescriptivesSchema(
    schemas.ListSchema
):


    class MetaOapg:
        items = schemas.StrSchema

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DescriptivesSchema':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> MetaOapg.items:
        return super().__getitem__(i)
SortSchema = schemas.StrSchema
FeaturedSchema = schemas.BoolSchema
PageSchema = schemas.IntSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'page_size': typing.Union[PageSizeSchema, decimal.Decimal, int, ],
        'category': typing.Union[CategorySchema, str, ],
        'gender': typing.Union[GenderSchema, str, ],
        'age': typing.Union[AgeSchema, str, ],
        'accent': typing.Union[AccentSchema, str, ],
        'search': typing.Union[SearchSchema, str, ],
        'use_cases': typing.Union[UseCasesSchema, list, tuple, ],
        'descriptives': typing.Union[DescriptivesSchema, list, tuple, ],
        'sort': typing.Union[SortSchema, str, ],
        'featured': typing.Union[FeaturedSchema, bool, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_page_size = api_client.QueryParameter(
    name="page_size",
    style=api_client.ParameterStyle.FORM,
    schema=PageSizeSchema,
    explode=True,
)
request_query_category = api_client.QueryParameter(
    name="category",
    style=api_client.ParameterStyle.FORM,
    schema=CategorySchema,
    explode=True,
)
request_query_gender = api_client.QueryParameter(
    name="gender",
    style=api_client.ParameterStyle.FORM,
    schema=GenderSchema,
    explode=True,
)
request_query_age = api_client.QueryParameter(
    name="age",
    style=api_client.ParameterStyle.FORM,
    schema=AgeSchema,
    explode=True,
)
request_query_accent = api_client.QueryParameter(
    name="accent",
    style=api_client.ParameterStyle.FORM,
    schema=AccentSchema,
    explode=True,
)
request_query_search = api_client.QueryParameter(
    name="search",
    style=api_client.ParameterStyle.FORM,
    schema=SearchSchema,
    explode=True,
)
request_query_use_cases = api_client.QueryParameter(
    name="use_cases",
    style=api_client.ParameterStyle.FORM,
    schema=UseCasesSchema,
    explode=True,
)
request_query_descriptives = api_client.QueryParameter(
    name="descriptives",
    style=api_client.ParameterStyle.FORM,
    schema=DescriptivesSchema,
    explode=True,
)
request_query_sort = api_client.QueryParameter(
    name="sort",
    style=api_client.ParameterStyle.FORM,
    schema=SortSchema,
    explode=True,
)
request_query_featured = api_client.QueryParameter(
    name="featured",
    style=api_client.ParameterStyle.FORM,
    schema=FeaturedSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
# Header params
XiApiKeySchema = schemas.StrSchema
RequestRequiredHeaderParams = typing_extensions.TypedDict(
    'RequestRequiredHeaderParams',
    {
    }
)
RequestOptionalHeaderParams = typing_extensions.TypedDict(
    'RequestOptionalHeaderParams',
    {
        'xi-api-key': typing.Union[XiApiKeySchema, str, ],
    },
    total=False
)


class RequestHeaderParams(RequestRequiredHeaderParams, RequestOptionalHeaderParams):
    pass


request_header_xi_api_key = api_client.HeaderParameter(
    name="xi-api-key",
    style=api_client.ParameterStyle.SIMPLE,
    schema=XiApiKeySchema,
)
SchemaFor200ResponseBodyApplicationJson = GetLibraryVoicesResponseModelSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: GetLibraryVoicesResponseModel


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: GetLibraryVoicesResponseModel


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor422ResponseBodyApplicationJson = HTTPValidationErrorSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: HTTPValidationError


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: HTTPValidationError


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_shared_voices_mapped_args(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _header_params = {}
        if page_size is not None:
            _query_params["page_size"] = page_size
        if category is not None:
            _query_params["category"] = category
        if gender is not None:
            _query_params["gender"] = gender
        if age is not None:
            _query_params["age"] = age
        if accent is not None:
            _query_params["accent"] = accent
        if search is not None:
            _query_params["search"] = search
        if use_cases is not None:
            _query_params["use_cases"] = use_cases
        if descriptives is not None:
            _query_params["descriptives"] = descriptives
        if sort is not None:
            _query_params["sort"] = sort
        if featured is not None:
            _query_params["featured"] = featured
        if page is not None:
            _query_params["page"] = page
        if xi_api_key is not None:
            _header_params["xi-api-key"] = xi_api_key
        args.query = _query_params
        args.header = _header_params
        return args

    async def _aget_shared_voices_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get Voices
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_page_size,
            request_query_category,
            request_query_gender,
            request_query_age,
            request_query_accent,
            request_query_search,
            request_query_use_cases,
            request_query_descriptives,
            request_query_sort,
            request_query_featured,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_xi_api_key,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/shared-voices',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_shared_voices_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get Voices
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_page_size,
            request_query_category,
            request_query_gender,
            request_query_age,
            request_query_accent,
            request_query_search,
            request_query_use_cases,
            request_query_descriptives,
            request_query_sort,
            request_query_featured,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_xi_api_key,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/shared-voices',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetSharedVoicesRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_shared_voices(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_shared_voices_mapped_args(
            page_size=page_size,
            category=category,
            gender=gender,
            age=age,
            accent=accent,
            search=search,
            use_cases=use_cases,
            descriptives=descriptives,
            sort=sort,
            featured=featured,
            page=page,
            xi_api_key=xi_api_key,
        )
        return await self._aget_shared_voices_oapg(
            query_params=args.query,
            header_params=args.header,
            **kwargs,
        )
    
    def get_shared_voices(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_shared_voices_mapped_args(
            page_size=page_size,
            category=category,
            gender=gender,
            age=age,
            accent=accent,
            search=search,
            use_cases=use_cases,
            descriptives=descriptives,
            sort=sort,
            featured=featured,
            page=page,
            xi_api_key=xi_api_key,
        )
        return self._get_shared_voices_oapg(
            query_params=args.query,
            header_params=args.header,
        )

class GetSharedVoices(BaseApi):

    async def aget_shared_voices(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> GetLibraryVoicesResponseModelPydantic:
        raw_response = await self.raw.aget_shared_voices(
            page_size=page_size,
            category=category,
            gender=gender,
            age=age,
            accent=accent,
            search=search,
            use_cases=use_cases,
            descriptives=descriptives,
            sort=sort,
            featured=featured,
            page=page,
            xi_api_key=xi_api_key,
            **kwargs,
        )
        if validate:
            return GetLibraryVoicesResponseModelPydantic(**raw_response.body)
        return api_client.construct_model_instance(GetLibraryVoicesResponseModelPydantic, raw_response.body)
    
    
    def get_shared_voices(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
        validate: bool = False,
    ) -> GetLibraryVoicesResponseModelPydantic:
        raw_response = self.raw.get_shared_voices(
            page_size=page_size,
            category=category,
            gender=gender,
            age=age,
            accent=accent,
            search=search,
            use_cases=use_cases,
            descriptives=descriptives,
            sort=sort,
            featured=featured,
            page=page,
            xi_api_key=xi_api_key,
        )
        if validate:
            return GetLibraryVoicesResponseModelPydantic(**raw_response.body)
        return api_client.construct_model_instance(GetLibraryVoicesResponseModelPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_shared_voices_mapped_args(
            page_size=page_size,
            category=category,
            gender=gender,
            age=age,
            accent=accent,
            search=search,
            use_cases=use_cases,
            descriptives=descriptives,
            sort=sort,
            featured=featured,
            page=page,
            xi_api_key=xi_api_key,
        )
        return await self._aget_shared_voices_oapg(
            query_params=args.query,
            header_params=args.header,
            **kwargs,
        )
    
    def get(
        self,
        page_size: typing.Optional[int] = None,
        category: typing.Optional[str] = None,
        gender: typing.Optional[str] = None,
        age: typing.Optional[str] = None,
        accent: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        use_cases: typing.Optional[typing.List[str]] = None,
        descriptives: typing.Optional[typing.List[str]] = None,
        sort: typing.Optional[str] = None,
        featured: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        xi_api_key: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_shared_voices_mapped_args(
            page_size=page_size,
            category=category,
            gender=gender,
            age=age,
            accent=accent,
            search=search,
            use_cases=use_cases,
            descriptives=descriptives,
            sort=sort,
            featured=featured,
            page=page,
            xi_api_key=xi_api_key,
        )
        return self._get_shared_voices_oapg(
            query_params=args.query,
            header_params=args.header,
        )

