# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.body_edit_voice_v1_voices_voice_id_edit_post_files import BodyEditVoiceV1VoicesVoiceIdEditPostFiles

class RequiredBodyEditVoiceV1VoicesVoiceIdEditPost(TypedDict):
    # The name that identifies this voice. This will be displayed in the dropdown of the website.
    name: str

class OptionalBodyEditVoiceV1VoicesVoiceIdEditPost(TypedDict, total=False):
    # How would you describe the voice?
    description: str

    files: BodyEditVoiceV1VoicesVoiceIdEditPostFiles

    # Serialized labels dictionary for the voice.
    labels: str

class BodyEditVoiceV1VoicesVoiceIdEditPost(RequiredBodyEditVoiceV1VoicesVoiceIdEditPost, OptionalBodyEditVoiceV1VoicesVoiceIdEditPost):
    pass
