# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.invoice_response_model import InvoiceResponseModel

class RequiredExtendedSubscriptionResponseModel(TypedDict):
    tier: str

    character_count: int

    character_limit: int

    can_extend_character_limit: bool

    allowed_to_extend_character_limit: bool

    next_character_count_reset_unix: int

    voice_limit: int

    max_voice_add_edits: int

    voice_add_edit_counter: int

    professional_voice_limit: int

    can_extend_voice_limit: bool

    can_use_instant_voice_cloning: bool

    can_use_professional_voice_cloning: bool

    currency: str

    status: str

    next_invoice: InvoiceResponseModel

    has_open_invoices: bool

class OptionalExtendedSubscriptionResponseModel(TypedDict, total=False):
    pass

class ExtendedSubscriptionResponseModel(RequiredExtendedSubscriptionResponseModel, OptionalExtendedSubscriptionResponseModel):
    pass
