# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLibraryVoiceResponseModel(TypedDict):
    description: str

    public_owner_id: str

    voice_id: str

    date_unix: int

    name: str

    accent: str

    gender: str

    age: str

    descriptive: str

    use_case: str

    category: str

    language: str

    preview_url: str

    usage_character_count_1y: int

    usage_character_count_7d: int

    cloned_by_count: int

    rate: typing.Union[int, float]

    free_users_allowed: bool

    live_moderation_enabled: bool

    notice_period: int

    instagram_username: str

    twitter_username: str

    youtube_username: str

    tiktok_username: str

    featured: bool

class OptionalLibraryVoiceResponseModel(TypedDict, total=False):
    pass

class LibraryVoiceResponseModel(RequiredLibraryVoiceResponseModel, OptionalLibraryVoiceResponseModel):
    pass
