# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.language_response_model import LanguageResponseModel

class RequiredModelResponseModel(TypedDict):
    description: str

    model_id: str

    name: str

    can_be_finetuned: bool

    can_do_text_to_speech: bool

    can_do_voice_conversion: bool

    can_use_style: bool

    can_use_speaker_boost: bool

    serves_pro_voices: bool

    token_cost_factor: typing.Union[int, float]

    requires_alpha_access: bool

    max_characters_request_free_user: int

    max_characters_request_subscribed_user: int

    languages: typing.List[LanguageResponseModel]

class OptionalModelResponseModel(TypedDict, total=False):
    pass

class ModelResponseModel(RequiredModelResponseModel, OptionalModelResponseModel):
    pass
