# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProjectResponseModel(TypedDict):
    title: str

    project_id: str

    name: str

    create_date_unix: int

    default_title_voice_id: str

    default_paragraph_voice_id: str

    default_model_id: str

    last_conversion_date_unix: int

    can_be_downloaded: bool

    author: str

    isbn_number: str

    volume_normalization: bool

    state: str

class OptionalProjectResponseModel(TypedDict, total=False):
    pass

class ProjectResponseModel(RequiredProjectResponseModel, OptionalProjectResponseModel):
    pass
