# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.feedback_response_model import FeedbackResponseModel

class RequiredSpeechHistoryItemResponseModel(TypedDict):
    history_item_id: str

    request_id: str

    voice_id: str

    model_id: str

    voice_name: str

    voice_category: str

    text: str

    date_unix: int

    character_count_change_from: int

    character_count_change_to: int

    content_type: str

    state: str

    settings: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    feedback: FeedbackResponseModel

    share_link_id: str

    source: str

class OptionalSpeechHistoryItemResponseModel(TypedDict, total=False):
    pass

class SpeechHistoryItemResponseModel(RequiredSpeechHistoryItemResponseModel, OptionalSpeechHistoryItemResponseModel):
    pass
