# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.subscription_response_model import SubscriptionResponseModel

class RequiredUserResponseModel(TypedDict):
    subscription: SubscriptionResponseModel

    is_new_user: bool

    xi_api_key: str

    can_use_delayed_payment_methods: bool

    is_onboarding_completed: bool

class OptionalUserResponseModel(TypedDict, total=False):
    first_name: str

class UserResponseModel(RequiredUserResponseModel, OptionalUserResponseModel):
    pass
