# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.fine_tuning_response_model import FineTuningResponseModel
from eleven_labs_python_sdk.type.sample_response_model import SampleResponseModel
from eleven_labs_python_sdk.type.voice_response_model_available_for_tiers import VoiceResponseModelAvailableForTiers
from eleven_labs_python_sdk.type.voice_response_model_high_quality_base_model_ids import VoiceResponseModelHighQualityBaseModelIds
from eleven_labs_python_sdk.type.voice_response_model_labels import VoiceResponseModelLabels
from eleven_labs_python_sdk.type.voice_settings_response_model import VoiceSettingsResponseModel
from eleven_labs_python_sdk.type.voice_sharing_response_model import VoiceSharingResponseModel
from eleven_labs_python_sdk.type.voice_verification_response_model import VoiceVerificationResponseModel

class RequiredVoiceResponseModel(TypedDict):
    description: str

    voice_id: str

    name: str

    samples: typing.List[SampleResponseModel]

    category: str

    fine_tuning: FineTuningResponseModel

    labels: VoiceResponseModelLabels

    preview_url: str

    available_for_tiers: VoiceResponseModelAvailableForTiers

    settings: VoiceSettingsResponseModel

    sharing: VoiceSharingResponseModel

    high_quality_base_model_ids: VoiceResponseModelHighQualityBaseModelIds

class OptionalVoiceResponseModel(TypedDict, total=False):
    safety_control: str

    voice_verification: VoiceVerificationResponseModel

class VoiceResponseModel(RequiredVoiceResponseModel, OptionalVoiceResponseModel):
    pass
