# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from eleven_labs_python_sdk.type.voice_sharing_response_model_labels import VoiceSharingResponseModelLabels
from eleven_labs_python_sdk.type.voice_sharing_response_model_whitelisted_emails import VoiceSharingResponseModelWhitelistedEmails

class RequiredVoiceSharingResponseModel(TypedDict):
    description: str

    status: str

    history_item_sample_id: str

    date_unix: int

    whitelisted_emails: VoiceSharingResponseModelWhitelistedEmails

    public_owner_id: str

    original_voice_id: str

    financial_rewards_enabled: bool

    free_users_allowed: bool

    live_moderation_enabled: bool

    rate: typing.Union[int, float]

    notice_period: int

    disable_at_unix: int

    voice_mixing_allowed: bool

    instagram_username: str

    twitter_username: str

    youtube_username: str

    tiktok_username: str

    featured: bool

    ban_reason: str

    liked_by_count: int

    cloned_by_count: int

    name: str

    labels: VoiceSharingResponseModelLabels

    review_status: str

    review_message: str

    enabled_in_library: bool

class OptionalVoiceSharingResponseModel(TypedDict, total=False):
    pass

class VoiceSharingResponseModel(RequiredVoiceSharingResponseModel, OptionalVoiceSharingResponseModel):
    pass
