# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost(BaseModel):
    # The new slug for the vanity link. For example, if you want the vanity link to be /blog/NEW_SLUG, enter NEW_SLUG.
    vanity_slug: str = Field(alias='vanity_slug')

    # The new URL that the vanity link should redirect to.
    target_url: str = Field(alias='target_url')

    # A new comment or description for the vanity link.
    comment: str = Field(alias='comment')
    class Config:
        arbitrary_types_allowed = True
