# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from eleven_labs_python_sdk.pydantic.body_edit_voice_v1_voices_voice_id_edit_post_files import BodyEditVoiceV1VoicesVoiceIdEditPostFiles

class BodyEditVoiceV1VoicesVoiceIdEditPost(BaseModel):
    # The name that identifies this voice. This will be displayed in the dropdown of the website.
    name: str = Field(alias='name')

    # How would you describe the voice?
    description: typing.Optional[str] = Field(None, alias='description')

    files: typing.Optional[BodyEditVoiceV1VoicesVoiceIdEditPostFiles] = Field(None, alias='files')

    # Serialized labels dictionary for the voice.
    labels: typing.Optional[str] = Field(None, alias='labels')
    class Config:
        arbitrary_types_allowed = True
