# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class BodyCreatesAudioNativeEnabledProjectV1AudioNativePost(BaseModel):
    # Project name.
    name: str = Field(alias='name')

    # Either txt or HTML input file containing the article content. HTML should be formatted as follows '&lt;html&gt;&lt;body&gt;&lt;div&gt;&lt;p&gt;Your content&lt;/p&gt;&lt;h5&gt;More of your content&lt;/h5&gt;&lt;p&gt;Some more of your content&lt;/p&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;'
    file: typing.IO = Field(alias='file')

    # Title used in the player and inserted at the top of the uploaded article. If not provided, the default title set in the Player settings is used.
    title: typing.Optional[str] = Field(None, alias='title')

    # Image URL used in the player. If not provided, default image set in the Player settings is used.
    image: typing.Optional[str] = Field(None, alias='image')

    # Author used in the player and inserted at the start of the uploaded article. If not provided, the default author set in the Player settings is used.
    author: typing.Optional[str] = Field(None, alias='author')

    # Whether to use small player or not. If not provided, default value set in the Player settings is used.
    small: typing.Optional[bool] = Field(None, alias='small')

    # Text color used in the player. If not provided, default text color set in the Player settings is used.
    text_color: typing.Optional[str] = Field(None, alias='text_color')

    # Background color used in the player. If not provided, default background color set in the Player settings is used.
    background_color: typing.Optional[str] = Field(None, alias='background_color')

    # Specifies for how many minutes to persist the session across page reloads. If not provided, default sessionization set in the Player settings is used.
    sessionization: typing.Optional[int] = Field(None, alias='sessionization')

    # Voice ID used to voice the content. If not provided, default voice ID set in the Player settings is used.
    voice_id: typing.Optional[str] = Field(None, alias='voice_id')

    # TTS Model ID used in the player. If not provided, default model ID set in the Player settings is used.
    model_id_: typing.Optional[str] = Field(None, alias='model_id')

    # Whether to auto convert the project to audio or not.
    auto_convert: typing.Optional[bool] = Field(None, alias='auto_convert')
    class Config:
        arbitrary_types_allowed = True
