# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from eleven_labs_python_sdk.pydantic.chapter_statistics_response_model import ChapterStatisticsResponseModel

class ChapterResponseModel(BaseModel):
    chapter_id: str = Field(alias='chapter_id')

    name: str = Field(alias='name')

    last_conversion_date_unix: int = Field(alias='last_conversion_date_unix')

    conversion_progress: typing.Union[int, float] = Field(alias='conversion_progress')

    can_be_downloaded: bool = Field(alias='can_be_downloaded')

    state: Literal["default", "converting"] = Field(alias='state')

    statistics: ChapterStatisticsResponseModel = Field(alias='statistics')
    class Config:
        arbitrary_types_allowed = True
