# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class FeedbackResponseModel(BaseModel):
    thumbs_up: bool = Field(alias='thumbs_up')

    feedback: str = Field(alias='feedback')

    emotions: bool = Field(alias='emotions')

    inaccurate_clone: bool = Field(alias='inaccurate_clone')

    glitches: bool = Field(alias='glitches')

    audio_quality: bool = Field(alias='audio_quality')

    other: bool = Field(alias='other')

    review_status: typing.Optional[str] = Field(None, alias='review_status')
    class Config:
        arbitrary_types_allowed = True
