# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from eleven_labs_python_sdk.pydantic.speech_history_item_response_model import SpeechHistoryItemResponseModel

class GetSpeechHistoryResponseModel(BaseModel):
    history: typing.List[SpeechHistoryItemResponseModel] = Field(alias='history')

    last_history_item_id: str = Field(alias='last_history_item_id')

    has_more: bool = Field(alias='has_more')
    class Config:
        arbitrary_types_allowed = True
