# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class LibraryVoiceResponseModel(BaseModel):
    description: str = Field(alias='description')

    public_owner_id: str = Field(alias='public_owner_id')

    voice_id: str = Field(alias='voice_id')

    date_unix: int = Field(alias='date_unix')

    name: str = Field(alias='name')

    accent: str = Field(alias='accent')

    gender: str = Field(alias='gender')

    age: str = Field(alias='age')

    descriptive: str = Field(alias='descriptive')

    use_case: str = Field(alias='use_case')

    category: str = Field(alias='category')

    language: str = Field(alias='language')

    preview_url: str = Field(alias='preview_url')

    usage_character_count_1y: int = Field(alias='usage_character_count_1y')

    usage_character_count_7d: int = Field(alias='usage_character_count_7d')

    cloned_by_count: int = Field(alias='cloned_by_count')

    rate: typing.Union[int, float] = Field(alias='rate')

    free_users_allowed: bool = Field(alias='free_users_allowed')

    live_moderation_enabled: bool = Field(alias='live_moderation_enabled')

    notice_period: int = Field(alias='notice_period')

    instagram_username: str = Field(alias='instagram_username')

    twitter_username: str = Field(alias='twitter_username')

    youtube_username: str = Field(alias='youtube_username')

    tiktok_username: str = Field(alias='tiktok_username')

    featured: bool = Field(alias='featured')
    class Config:
        arbitrary_types_allowed = True
