# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from eleven_labs_python_sdk.pydantic.subscription_response_model import SubscriptionResponseModel

class UserResponseModel(BaseModel):
    subscription: SubscriptionResponseModel = Field(alias='subscription')

    is_new_user: bool = Field(alias='is_new_user')

    xi_api_key: str = Field(alias='xi_api_key')

    can_use_delayed_payment_methods: bool = Field(alias='can_use_delayed_payment_methods')

    is_onboarding_completed: bool = Field(alias='is_onboarding_completed')

    first_name: typing.Optional[str] = Field(None, alias='first_name')
    class Config:
        arbitrary_types_allowed = True
